name: Docker CI

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    strategy:
      matrix:
        image:
          - 'mathcomp/mathcomp:1.10.0-coq-8.11'
          - 'mathcomp/mathcomp:1.12.0-coq-8.12'
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-incomplete-games-rjcia2021.opam'
          custom_image: ${{ matrix.image }}
